---
toc: false
---

# Bakgrund {.unnumbered}

RISE har på uppdrag av Länsstyrelsen i Stockholm tagit fram en kunskapssammanställning om risk- och skyddsfaktorer för multipla problemutfall samt insatser för att arbeta förebyggande och främjande. Nu pågår ett arbete för att kvalitetssäkra mätning av relevanta faktorer, samt visualisera data för användning i samverkan med kommuner.

Kunskapssammanställningen Risk- och skyddsfaktorer – vad vet vi och vad kan göras med kunskapen? finns tillgänglig i DIVA-databasen och bakgrundsmaterial, inklusive källkod för att skapa figurerna i rapporten, finns att ladda ner från Open Science Foundations hemsida: https://osf.io/935b6/. Allt material har publicerats under den öppna licensen Creative Commons Attribution 4.0 International som innebär att det är fritt att dela och använda/vidareutveckla materialet, även för kommersiella syften, så länge hänvisning ges till rapporten.

Nästa steg i arbetet handlar om mätning av risk- och skyddsfaktorer, där Stockholmsenkäten spelar en central roll. Stockholmsenkäten genomförs varannat år genom samarbete med skolor, där årskurs 9 och gymnasiets åk 2 tillfrågas om anonymt deltagande. Ett omfattande arbete har genomförts för att psykometriskt utvärdera vilka index som kan användas för att representera risk- och skyddsfaktorer utifrån Stockholmsenkätens frågor, baserat på data från 2006 till 2020. Psykometriska analyser utförs primärt med Rasch-metodik, en form av modern testteori.

Mera information finns på: https://www.ri.se/sv/vad-vi-gor/projekt/data-i-dialog-risk-och-skyddsfaktorer-for-barn-och-unga 